config/routes.rb
Rails.application.routes.draw do
  get 'lottery/wheel'

  get 'products/for_sale'
  get 'products/order'

  get 'products/search',to: 'products#search', as: 'search_product'
  get 'products/tag',to: 'products#tag', as: 'tag_product'
  get 'collections/show'
  post 'collections/new'
  post 'collections/remove'
  post 'orders/remove'
  post 'products/remove'
  post 'products/selled'
  post 'products/cancel'
  post 'products/:id/orders', to: 'orders#create', as: 'new_order'
  post 'products/:id/edit', to: 'products#edit'
  post 'products/create'

  resources :products
  resources :orders

  mount RailsAdmin::Engine => '/admin/renmiaoshinvde', as: 'rails_admin'

  devise_for :users , controllers: {registrations: "registrations"}
  resources :users

  get 'home/index'
  get 'home/minor'
  get 'other/check', to: 'other#check' , as: 'check'

  get 'user_edit/show'
  patch 'user_edit/edit'

  post 'orders/notify_email', to: 'orders#notify_email'
  post 'orders/notify_text', to: 'orders#notify_text'

  root 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :orders, :dependent => :delete_all
  has_many :collections, :dependent => :delete_all
  #{x: 4, y: 0}
  #{:x => 4, :y => 0}

  #has_attached_file :photo0, styles: { small: "64x64", med: "100x100", large: "200x200", thumb: "400x400#" },
  has_attached_file :photo0, styles: { thumb: "400x400#" },
    default_url: "/images/empty.jpg"

  validates_attachment_content_type :photo0, content_type: [/\Aimage\/.*\Z/, nil, ""]

  #has_attached_file :photo1, styles: { small: "64x64", med: "100x100", large: "200x200", thumb: "400x400#" },
  has_attached_file :photo1, styles: { thumb: "400x400#" },
    default_url: "/images/empty.jpg"

  validates_attachment_content_type :photo1, content_type: [/\Aimage\/.*\Z/, nil, ""]

  #has_attached_file :photo2, styles: { small: "64x64", med: "100x100", large: "200x200", thumb: "400x400#" },
  has_attached_file :photo2, styles: { thumb: "400x400#" },
    default_url: "/images/empty.jpg"

  validates_attachment_content_type :photo2, content_type: [/\Aimage\/.*\Z/, nil, ""]

  #has_attached_file :photo3, styles: { small: "64x64", med: "100x100", large: "200x200", thumb: "400x400#" },
  has_attached_file :photo3, styles: { thumb: "400x400#" },
    default_url: "/images/empty.jpg"
  validates_attachment_content_type :photo3, content_type: [/\Aimage\/.*\Z/, nil, ""]

  #has_attached_file :photo4, styles: { small: "64x64", med: "100x100", large: "200x200", thumb: "400x400#" },
  has_attached_file :photo4, styles: { thumb: "400x400#" },
    default_url: "/images/empty.jpg"
  validates_attachment_content_type :photo4, content_type: [/\Aimage\/.*\Z/, nil, ""]


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # status 0 dicussion 1 close 2 selled 3
  before_action :authenticate_user!
  require 'rqrcode_png'
  def show
    @order = Order.new
    @product = Product.find params[:id]
    @orders = @product.orders.order(price: :desc)

    @already_buy = false
    for o in @orders
      if o.user == current_user
        @already_buy = true
        break
      end
    end

    @iscollection = 0
    for i in current_user.collections
      # puts "nimas"
      # puts i.product_id
      # puts params[:id]
      if i.product_id == params[:id].to_i
        @iscollection = 1
      end
    end

    puts request.original_url
    url =  'http://soavm.chinacloudapp.cn/products/' + @product.id.to_i.to_s
    @qr = RQRCode::QRCode.new(url).to_img.resize(200, 200).to_data_url
    #qr = RQRCode::QRCode.new(request.original_url, :size => 4, :level => :h )

  end

  def new
    @product = Product.new
    #puts "2312312"
  end

  def create
    #skip_before_action :verify_authenticity_token
    # puts "debug ++++++++++++++++++++++++++ \n"
    # puts params
    #print(params[:pic])

    #print(params[:title])

    puts "create product"
    if params[:product][:photo0]
      p0 = params[:product][:photo0]
    else
      p0 = nil
    end

    if params[:product][:photo1]
      p1 = params[:product][:photo1]
    else
      p1 = p0
    end

    if params[:product][:photo2]
      p2 = params[:product][:photo2]
    else
      p2 = p0
    end

    if params[:product][:photo3]
      p3 = params[:product][:photo3]
    else
      p3 = p0
    end

    if params[:product][:photo4]
      p4 = params[:product][:photo4]
    else
      p4 = p0
    end
    # puts "productdebug"
    puts p0
    puts p1
    puts p2
    puts p3
    puts p4

    @product = current_user.products.build(
      title: params[:title],
      price: params[:price],
      description: params[:description],
      tag: params[:tag],
      photo0: p0,
      photo1: p1,
      photo2: p2,
      photo3: p3,
      photo4: p4
    )
    # puts @product
    puts "start save product"
    @product.save
    redirect_to product_path(@product)
  end

  def for_sale
    # puts current_user.id
    @products = Product.where(:user_id => current_user.id).order("updated_at DESC").all;
  end

  def default_value(l, d) #not work
    if params.has_key?(:l)
      # puts "has key +++++++++++++++++++++"
      return params[l]
    else
      # puts "no key +++++++++++++++++++++"
      return d
    end
  end

  def search
    page_limit = 30
    @page = Integer(params.has_key?("page") ? params["page"] : 1)
    limitl = (@page-1)*page_limit
    limitr = page_limit
    @search_content = "%" + params["query"] + "%"
    sql = ActiveRecord::Base.send(:sanitize_sql_array, ["select * from products where (tag like ? or title like ?
      or description like ?) order by id DESC limit ?, ?", @search_content, @search_content, @search_content, limitl, limitr])

    # puts sql
    # @products = Product.find_by_sql("select * from products where
    #   (tag like '%#{@search_content}%' or
    #   title like '%#{@search_content}%' or
    #   description like '%#{@search_content}%' and status = 0)
    #   order by id limit #{limitl}, #{limitr}")
    @products = Product.find_by_sql(sql)

    sql = ActiveRecord::Base.send(:sanitize_sql_array, ["select id from products where (tag like ? or title like ?
      or description like ?)", @search_content, @search_content, @search_content])
    @product_number = Product.find_by_sql(sql).count
    # puts "product number:" +  String(product_number)
    # puts "product number:" +  String(product_number / page_limit)
    @lastpage = (Float(@product_number) / page_limit).ceil
    @search_content = @search_content[1..-2]
  end



  def tag

    page_limit = 30
    @page = Integer(params.has_key?("page") ? params["page"] : 1)
    limitl = (@page-1)*page_limit
    limitr = page_limit
    @search_content = "%" + params["query"] + "%"

    sql = ActiveRecord::Base.send(:sanitize_sql_array, ["select * from products where (tag like ?) order by id DESC limit ?, ?", @search_content, limitl, limitr])
    @products = Product.find_by_sql(sql)

    sql = ActiveRecord::Base.send(:sanitize_sql_array, ["select * from products where (tag like ?)", @search_content])
    @product_number = Product.find_by_sql(sql).count
    @lastpage = (Float(@product_number) / page_limit).ceil
    @search_content = @search_content[1..-2]
  end

  def change_status_byorder(order, new_status)
    product = order.product
    product.status = new_status
    product.save
  end

  def remove
    product = Product.find(params[:id])
    # for i in product.orders
      # i.destroy
    # end
    product.destroy
    # product.status = 3
    # product.save
    @object = {"status":"success"}
    render :json => @object
  end

  def selled
    product = Product.find(params[:id])
    # for i in product.orders
      # i.destroy
    # end
    # product.destroy
    product.status = 2
    for i in product.orders
      if i.status == 1
        i.status = 2
        i.save
      end
    end
    product.save
    @object = {"status":"success"}
    render :json => @object
  end

  def cancel
    product = Product.find(params[:id])
    product.status = 0
    for i in product.orders
      if i.status == 1
        i.status = 0
        i.save
      end
    end
    product.save
    @object = {"status":"success"}
    render :json => @object
  end

  def edit
    @product = Product.find(params[:id])
    #@product.price = params[:price]
    @product.description = params[:description]
    @product.save
    redirect_to product_path(@product)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_order_list.html.erb
<div class="project-list">

  <table class="table table-hover">
    <tbody>
      <% @orders.each do |e| %>
      <tr>

        <td class="project-people col-lg-2">
          <a href=""><img alt="image" class="img-circle" src="<%= e.user.avatar.url %>"></a>
          <%= e.user.nickname %>
        </td>

        <td class="project-completion col-lg-1">
          <span class="label label-warning">￥<%= e.price %></span>
        </td>


        <td class="project-title col-lg-4">
          <strong><%= e.description %></strong>
          <br>
          <small><%= e.created_at.strftime("%Y-%m-%d")%></small>
        </td>



        <td class="project-contact col-lg-3">
            <% if current_user == @product.user && @product.status != 2%>
              <button class="btn btn-success btn-sm demo4" name = <%= e.id %> >发送短信</button>
              <button class="btn btn-primary btn-sm demo3" name = <%= e.id %> >发送邮件</button>
            <% end %>
        </td>

        <td class="project-completion col-lg-1">
          <% if (e.status == 0) %>
          <span class="label label-info">等待中</span>
          <% elsif (e.status == 1) %>
          <span class="label label-warning">联系中</span>
          <% elsif (e.status == 2) %>
          <span class="label label-success">已收货</span>
          <% end %>
        </td>
        <td class="project-completion col-lg-1">
          <%if current_user == e.user%>
          <button type="button" class="close cancel_btn" oid = <%= e.id %> style="float:left;"><span aria-hidden="true">&times;</span></button>
          <%end%>
        </td>

      </tr>
      <% end %>

    </tbody>
  </table>
</div>

app/views/products/_qrcode.html.erb
<div class="modal inmodal fade" id="myModal6" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h5 class="modal-title">宝贝二维码</h5>
                        </div>
                        <div class="modal-body" >

                          <div class="vertical-timeline-block">
                              <div class="vertical-timeline-content" style="margin-left: 0px;">
                                  <div class="vertical-container" style="text-align:center">
                            <%=image_tag @qr%>
                          </div>
                        </div>
                      </div>
                            <div class="vertical-timeline-block">
                                <div class="vertical-timeline-content" style="margin-left: 0px;">
                                    <div class="vertical-container">
                                    <h4>1.用微信扫描二维码</h4>
                                    <h4>2.点击右上角的"三个点",选择分享到朋友圈</h4>
                                    <h4>3.编辑你的宣传语</h4>
                                    <h4>4.发送</h4>
                                </div>
                            </div>
                          </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                        </div>
                    </div>
                </div>
            </div>

app/views/products/for_sale.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="pull-right"><a type="button" class="btn btn-w-m btn-primary btn-lg" href="<%= new_product_path %>">我要卖东西</a></div>
  <h2>我卖的</h2>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

<% @products.each do |e| %>
<div class="vote-item">
    <div class="row">

      <div class="col-md-1">
        <%if e.orders.count > 0%>
          <span class="label label-danger" style="position: absolute;top: -6px;"><%= e.orders.count %></span>
        <%end%>
          <a href="<%= product_path(e)%>"><img alt="image" src= <%= e.photo0.url(:thumb) %> height="70" width="70"></a>
      </div>

        <div class="col-md-4">

            <a href="<%= product_path(e)%>" class="vote-title">
                <%= e.title %>
            </a>
            <div class="vote-info">
                <i class="fa fa-comments-o"></i> 订单 (<%= e.orders.count %>)&nbsp
                <i class="fa fa-clock-o"></i>更新于 (<%= e.updated_at %>)&nbsp
                <!-- <i class="fa fa-user"></i> <a href="#"></a> -->
            </div>
        </div>

        <div class="col-md-4" style="line-height:70px;">
          <%if e.status == 0%>
            <span class="label label-primary">正在出售</span>
          <%elsif e.status == 1%>
            <span class="label label-warning">正在联系</span>
          <%elsif e.status == 2%>
            <span class="label label-success">已卖出</span>
          <%end%>
        </div>

        <div class="col-md-3 button-f">
          <div class="button-c" style="right:20px">
            <%if e.status == 1%>
              <button class="btn btn-success btn-md selled_btn" name = <%= e.id %> >已卖出</button>
              <button class="btn btn-primary btn-md return_btn" name = <%= e.id %> >重新出售</button>
              <%end%>
            <button class="btn btn-danger btn-md delete_btn" name = <%= e.id %> >删&nbsp &nbsp除</button>&nbsp
          </div>
        </div>



    </div>
</div>


<% end %>


</div>

<script>
$(function(){

  $('.delete_btn').click(function() {
    var pid = $(this).attr("name");
    swal({
      title: "确定删除商品",
      type: "warning",
      showCancelButton: true,
      confirmButtonColor: "#DD6B55",
      confirmButtonText: "确定",
      closeOnConfirm: false,
      cancelButtonText: "取消"
    },
    function (isConfirm) {
      if (isConfirm) {
        $.ajax({
                  type: "POST",
                  url: "/products/remove",
                  data: {id : pid},
                  dataType: "json",
                  success: function(data){
                    location=location;
                    swal("成功", "已删除商品", "success");
                  }
                });
      }
    });
  });

  $('.selled_btn').click(function() {
    $.ajax({
              type: "POST",
              url: "/products/selled",
              data: {id : $(this).attr("name")},
              dataType: "json",
              success: function(data){
                location=location;
              }
            });
  }
  );

  $('.return_btn').click(function() {
    $.ajax({
              type: "POST",
              url: "/products/cancel",
              data: {id : $(this).attr("name")},
              dataType: "json",
              success: function(data){
                location=location;
              }
            });
  }
  );

});

</script>

app/views/products/new.html.erb
<%= csrf_meta_tag %>

<div class="wrapper wrapper-content animated fadeInRight">

  <div>
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h3>添加商品</h3>
      </div>
      <div class="ibox-content">
        <div class="row">
          <%= form_for @product, url: {action: "create"} ,:html => {:id => 'mydropzone', :enctype => 'multipart/form-data'} do |f| %>

          <!-- <form id="my-awesome-dropzone" enctype='multipart/form-data' multipart=true method="post" class="dropzone" action="create"> -->
          <div class="col-sm-6 b-r">
            <div class="form-group"><label>商品名称</label>
              <input type="text" placeholder="20字以内" name="title" class="form-control" id="title"
                     required="" maxlength="20" ></div>

              <div class="form-group"><label>标签</label>
                <div class="input-group" name="tag">
                  <select data-placeholder="选择标签（至多3个）" class="chosen-select" multiple style="width:350px;" tabindex="4" name="tag" >
                    <option value="电子产品">电子产品</option>
                    <option value="衣服">衣服</option>
                    <option value="生活用品">生活用品</option>
                    <option value="书籍">书籍</option>
                    <option value="美妆">美妆</option>
                    <option value="体育">体育</option>
                    <option value="动漫">动漫</option>
                    <option value="其他">其他</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label>最低价格</label>
                <input type="text" name="price" class="form-control" required="" placeholder="请不要超过8位数~谢谢" onkeypress='return event.charCode >= 48 && event.charCode <= 57' maxlength="8">
              </div>
                <div class="form-group">
                  <label >描述</label>
                  <textarea type="text" rows="3" name="description" class="form-control" required="" maxlength="200" placeholder="200字以内"></textarea>
                  <input type="hidden" name="tag" id="form_tag"> </input>
                </div>

                <button class="btn btn-lg btn-primary" type="submit"><strong>提交</strong></button>

              </div>

              <div class="col-sm-6">
                <small>请上传至少一张图片，且每张图片大小不超过3M </small>
                <div class="row">

                  <div class="col-xs-3">
                    <div style="height:100px;width:100px;">
                      <img id="target_0" alt="image" src="/images/e2.jpeg" height="99" width="99" />
                    </div>
                    <div class="fileUpload btn btn-white" id="g0" style ="display:block;" >
                      <span>上传图片</span>
                      <input required="" type="file" class="upload" name="product[photo0]" id="pictureInput0" accept="image/png, image/jpeg"/>
                    </div>
                    <button class="fileUpload btn btn-danger" id="cancel_0" style="display:none;margin-left: 22px;" type="button">取消</button>
                  </div>

                  <div class="col-xs-3">
                    <div style="height:100px;width:100px;">
                      <img id="target_1" alt="image" src="/images/e2.jpeg" height="99" width="99" />
                    </div>
                    <div class="fileUpload btn btn-white" id="g1" style ="display:block;" >
                      <span>上传图片</span>
                      <input type="file" class="upload" name="product[photo1]" id="pictureInput1" accept="image/png, image/jpeg"/>
                    </div>
                    <button class="fileUpload btn btn-danger" id="cancel_1" style="display:none;margin-left: 22px;" type="button">取消</button>
                  </div>

                  <div class="col-xs-3">
                    <div style="height:100px;width:100px;">
                      <img id="target_2" alt="image" src="/images/e2.jpeg" height="99" width="99" />
                    </div>
                    <div class="fileUpload btn btn-white" id="g2" style ="display:block;" >
                      <span>上传图片</span>
                      <input type="file" class="upload" name="product[photo2]" id="pictureInput2" accept="image/png, image/jpeg"/>
                    </div>
                    <button class="fileUpload btn btn-danger" id="cancel_2" style="display:none;margin-left: 22px;" type="button">取消</button>
                  </div>
                </div>
              </br>

              <div class="row">

                <div class="col-xs-3">
                  <div style="height:100px;width:100px;">
                    <img id="target_3" alt="image" src="/images/e2.jpeg" height="99" width="99" />
                  </div>
                  <div class="fileUpload btn btn-white" id="g3" style ="display:block;" >
                    <span>上传图片</span>
                    <input type="file" class="upload" name="product[photo3]" id="pictureInput3" accept="image/png, image/jpeg"/>
                  </div>
                  <button class="fileUpload btn btn-danger" id="cancel_3" style="display:none;margin-left: 22px;" type="button">取消</button>
                </div>
                <div class="col-xs-3">
                  <div style="height:100px;width:100px;">
                    <img id="target_4" alt="image" src="/images/e2.jpeg" height="99" width="99" />
                  </div>
                  <div class="fileUpload btn btn-white" id="g4" style ="display:block;" >
                    <span>上传图片</span>
                    <input type="file" class="upload" name="product[photo4]" id="pictureInput4" accept="image/png, image/jpeg"/>
                  </div>
                  <button class="fileUpload btn btn-danger" id="cancel_4" style="display:none;margin-left: 22px;" type="button">取消</button>
                </div>

              </div>

            </div>

            <hr>




          </form>

          <% end %>

        </div>

      </div>

    </div>
  </div>
</div>
</div>

</div>


<script type="text/javascript">


$(function() {

  function cancel(picinput,cancel,taget,g)
  {
    document.getElementById(picinput).value = "";
    document.getElementById(cancel).style.display = 'none'
    document.getElementById(taget).src="/images/e2.jpeg";
    document.getElementById(g).style.display = 'block'
  }

  function show(cancel,taget,g,file)
  {
    document.getElementById(taget).src=file;
    document.getElementById(cancel).style.display = 'inline'
    document.getElementById(g).style.display = 'none'
  }

  function check(image) {
    if(image.size > 3*1024*1024) {
      swal({
                title: "文件超过3M",
                text: "请裁剪后上传~"
            });
      return false
    }else {
      return true
    }
  }


  $('#pictureInput0').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    if(check(image)) {
    var reader = new FileReader();
    reader.onload = function(file) {
      show('cancel_0','target_0','g0',file.target.result)
    }
    reader.readAsDataURL(image);
    console.log(files);
  }
  else {
    cancel("pictureInput0","cancel_0","target_0","g0")
  }
  });
  $("#cancel_0").click(function(){
    cancel("pictureInput0","cancel_0","target_0","g0")
  })

  $('#pictureInput1').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    if(check(image)) {
    var reader = new FileReader();
    reader.onload = function(file) {
      show('cancel_1','target_1','g1',file.target.result)
    }
    reader.readAsDataURL(image);
    console.log(files);
  }
  else {
    cancel("pictureInput1","cancel_1","target_1","g1")
  }

  });
  $("#cancel_1").click(function(){
    cancel("pictureInput1","cancel_1","target_1","g1")
  })

  $('#pictureInput2').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    if(check(image)) {
    var reader = new FileReader();
    reader.onload = function(file) {
      show('cancel_2','target_2','g2',file.target.result)
    }
    reader.readAsDataURL(image);
    console.log(files);
  }else {
    cancel("pictureInput2","cancel_2","target_2","g2")
  }
  });
  $("#cancel_2").click(function(){
    cancel("pictureInput2","cancel_2","target_2","g2")
  })

  $('#pictureInput3').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    if(check(image)) {
    var reader = new FileReader();
    reader.onload = function(file) {
      show('cancel_3','target_3','g3',file.target.result)
    }
    reader.readAsDataURL(image);
    console.log(files);
  } else {
    cancel("pictureInput3","cancel_3","target_3","g3")
  }
  });
  $("#cancel_3").click(function(){
    cancel("pictureInput3","cancel_3","target_3","g3")
  })

  $('#pictureInput4').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    if(check(image)) {
    var reader = new FileReader();
    reader.onload = function(file) {
      show('cancel_4','target_4','g4',file.target.result)
    }
    reader.readAsDataURL(image);
    console.log(files);
  }
  else {
    cancel("pictureInput4","cancel_4","target_4","g4")
  }
  });
  $("#cancel_4").click(function(){
    cancel("pictureInput4","cancel_4","target_4","g4")
  })


  $('.chosen-select').chosen({ max_selected_options: 3 });
  $(".chosen-select").chosen().change(function(v) {
    $("#form_tag").val($(this).val());
  });
});

</script>

app/views/products/search.html.erb
<div class="wrapper wrapper-content animated fadeInRight">

  <h2>搜索<strong><%= @search_content %></strong>的结果 <small>共<%=@product_number%>条</small></h2>
  <div class="row">
    <div class="col-lg-12">

      <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">

          <% @products.each do |e|%>
          <div class="col-md-2">
            <div class="ibox">
              <div class="ibox-content product-box">
                <div class="product-imitation">
                  <a href="<%= product_path(e) %>" target="_blank"><img alt="image" src="<%= e.photo0.url(:thumb) %>" style = "width:100%"></a>
                </div>
                <div class="product-desc">
                  <span class="product-price">
                    ￥<%= e.price %>
                  </span>
                  <a href="<%= product_path(e) %>" target="_blank" class="product-name pname"> <%= e.title %></a>

                  <div class="small m-t-xs ptext">
                    <%= e.description.length > 20 ? e.description[0,20]+"..." : e.description %>
                  </div>

                  <%if e.status == 0%>
                    <span class="label label-primary">正在出售</span>
                  <%elsif e.status == 1%>
                    <span class="label label-warning">正在联系</span>
                  <%elsif e.status == 2%>
                    <span class="label label-success">已卖出</span>
                  <%end%>

                </div>
              </div>
            </div>
          </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>

  <div id="pagination" style="text-align:center">
  <ul class="pagination pagination-content">
    <%if(@lastpage > 0) %>
    <%if(@page>1) %>
    <li><a href="search?query=<%=@search_content%>&page=<%=@page-1%>"><</a></li>
    <% end %>
    <%if(@page>2) %>
      <li><a href="search?query=<%=@search_content%>&page=1">1</a></li>
      <li><a href="">..</a></li>
    <%end%>

    <%for i in [1,@page-1].max..(@page-1)%>
      <li><a href="search?query=<%=@search_content%>&page=<%=i%>"><%=i%></a></li>
    <% end %>
    <li><a href=""><strong><%=@page%></strong></a></li>
    <%for i in (@page+1)..[@page+1,@lastpage].min%>
      <li><a href="search?query=<%=@search_content%>&page=<%=i%>"><%=i%></a></li>
    <% end %>

    <%if(@page<@lastpage-1) %>
      <li><a href="">..</a></li>
      <li><a href="search?query=<%=@search_content%>&page=<%=@lastpage%>"><%=@lastpage%></a></li>
    <%end%>

      <%if(@page != @lastpage && @lastpage!=0) %>
        <li><a href="search?query=<%=@search_content%>&page=<%=@page+1%>">></a></li>
      <%end %>
    <%else%>
      <h2 style="text-align: center;">抱歉，没有结果</h2>
    <%end%>
  </ul>
</div>



</div>
</div>

app/views/products/tag.html.erb
<div class="wrapper wrapper-content animated fadeInRight">

  <h2>标签结果 <small>共<%=@product_number%>条</small></h2>
  <div class="row">
    <div class="col-lg-12">

      <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">

          <% @products.each do |e|%>
          <div class="col-md-2">
            <div class="ibox">
              <div class="ibox-content product-box">
                <div class="product-imitation">
                  <a href="<%= product_path(e) %>" target="_blank"><img alt="image" src="<%= e.photo0.url(:thumb) %>" style = "width:100%"></a>
                </div>
                <div class="product-desc">
                  <span class="product-price">
                    ￥<%= e.price %>
                  </span>
                  <a href="<%= product_path(e) %>" target="_blank" class="product-name pname"> <%= e.title %></a>

                  <div class="small m-t-xs ptext">
                    <%= e.description.length > 20 ? e.description[0,20]+"..." : e.description %>
                  </div>

                  <%if e.status == 0%>
                    <span class="label label-primary">正在出售</span>
                  <%elsif e.status == 1%>
                    <span class="label label-warning">正在联系</span>
                  <%elsif e.status == 2%>
                    <span class="label label-success">已卖出</span>
                  <%end%>

                </div>
              </div>
            </div>
          </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
  <div id="pagination" style="text-align:center">
  <ul class="pagination pagination-content">
    <%if(@lastpage > 0) %>
    <%if(@page>1) %>
    <li><a href="tag?query=<%=@search_content%>&page=<%=@page-1%>"><</a></li>
    <% end %>
    <%if(@page>2) %>
      <li><a href="tag?query=<%=@search_content%>&page=1">1</a></li>
      <li><a href="">..</a></li>
    <%end%>

    <%for i in [1,@page-1].max..(@page-1)%>
      <li><a href="tag?query=<%=@search_content%>&page=<%=i%>"><%=i%></a></li>
    <% end %>
    <li><a href=""><strong><%=@page%></strong></a></li>
    <%for i in (@page+1)..[@page+1,@lastpage].min%>
      <li><a href="tag?query=<%=@search_content%>&page=<%=i%>"><%=i%></a></li>
    <% end %>

    <%if(@page<@lastpage-1) %>
      <li><a href="">..</a></li>
      <li><a href="tag?query=<%=@search_content%>&page=<%=@lastpage%>"><%=@lastpage%></a></li>
    <%end%>

      <%if(@page != @lastpage && @lastpage!=0) %>
        <li><a href="tag?query=<%=@search_content%>&page=<%=@page+1%>">></a></li>
      <%end %>
    <%else%>
      <h2 style="text-align: center;">抱歉，没有结果</h2>
    <%end%>
  </ul>
</div>


</div>