config/routes.rb
Rails.application.routes.draw do
  get 'lottery/wheel'

  get 'products/for_sale'
  get 'products/order'

  get 'products/search',to: 'products#search', as: 'search_product'
  get 'products/tag',to: 'products#tag', as: 'tag_product'
  get 'collections/show'
  post 'collections/new'
  post 'collections/remove'
  post 'orders/remove'
  post 'products/remove'
  post 'products/selled'
  post 'products/cancel'
  post 'products/:id/orders', to: 'orders#create', as: 'new_order'
  post 'products/:id/edit', to: 'products#edit'
  post 'products/create'

  resources :products
  resources :orders

  mount RailsAdmin::Engine => '/admin/renmiaoshinvde', as: 'rails_admin'

  devise_for :users , controllers: {registrations: "registrations"}
  resources :users

  get 'home/index'
  get 'home/minor'
  get 'other/check', to: 'other#check' , as: 'check'

  get 'user_edit/show'
  patch 'user_edit/edit'

  post 'orders/notify_email', to: 'orders#notify_email'
  post 'orders/notify_text', to: 'orders#notify_text'

  root 'home#index'

end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        <%= current_user.email %>
    </div>
    <div>
        <strong>Copyright</strong> SOA打得不错小组 &copy; 2016-2017
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">

          <li class="nav-header">
              <div class="dropdown profile-element" style="height: 100px;">
                  <span>
                    <%= link_to user_edit_show_path do %>
                    <% if current_user != nil %>
                      <img alt="image" class="img-circle" src="<%= current_user.avatar.url(:small) %>" height="70" width="70" />
                    <% end %>
                    <% end %>
                  </span>
                      <span class="clear">
                          <span class="block m-t-xs">
                            <% if current_user != nil %>
                              <strong class="font-bold" style="color:#a7b1c2"><%= current_user.nickname %></strong>
                            <% end %>
                          </span>
                          <span class="block m-t-xs">
                            <% if current_user != nil %>
                              <small style="color:#a7b1c2"><%= current_user.email %></small>
                            <% end %>
                          </span>
                      </span>
              </div>

          </li>



          <li class="<%= 'active' %>">
                <a href=""><i class="fa fa-yelp"></i> <span class="nav-label">我要买</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                  <li class="<%= 'active' if current_page?('/products/tag?query=电子产品') %>">
                      <%= link_to "/products/tag?query=电子产品" do %>
                      <i class="fa fa-laptop"></i> <span class="nav-label">电子产品</span>
                      <% end %>
                  </li>

                  <li class="<%= 'active' if current_page?('/products/tag?query=衣服') %>">
                      <%= link_to "/products/tag?query=衣服" do %>
                      <i class="fa fa-gift"></i> <span class="nav-label">衣服</span>
                      <% end %>
                  </li>
                  <li class="<%= 'active' if current_page?('/products/tag?query=生活用品') %>">
                      <%= link_to "/products/tag?query=生活用品" do %>
                      <i class="fa fa-suitcase"></i> <span class="nav-label">生活用品</span>
                      <% end %>
                  </li>
                  <li class="<%= 'active' if current_page?('/products/tag?query=书籍') %>">
                      <%= link_to "/products/tag?query=书籍" do %>
                      <i class="fa fa-book"></i> <span class="nav-label">书籍</span>
                      <% end %>
                  </li>
                  <li class="<%= 'active' if current_page?('/products/tag?query=美妆') %>">
                      <%= link_to "/products/tag?query=美妆" do %>
                      <i class="fa fa-pagelines"></i> <span class="nav-label">美妆</span>
                      <% end %>
                  </li>
                  <li class="<%= 'active' if current_page?('/products/tag?query=体育') %>">
                      <%= link_to "/products/tag?query=体育" do %>
                      <i class="fa fa-futbol-o"></i> <span class="nav-label">体育</span>
                      <% end %>
                  </li>
                  <li class="<%= 'active' if current_page?('/products/tag?query=动漫') %>">
                      <%= link_to "/products/tag?query=动漫" do %>
                      <i class="fa fa-paw"></i> <span class="nav-label">动漫</span>
                      <% end %>
                  </li>
                  <li class="<%= 'active' if current_page?('/products/tag?query=其他') %>">
                      <%= link_to "/products/tag?query=其他" do %>
                      <i class="fa fa-paw"></i> <span class="nav-label">其他</span>
                      <% end %>
                  </li>
                  <li class="<%= 'active' if current_page?('/products/search?query=') %>">
                      <%= link_to "/products/search?query=" do %>
                      <i class="fa fa-database"></i> <span class="nav-label">全部</span>
                      <% end %>
                  </li>

                </ul>
            </li>

            <li class="<%= 'active' if current_page?('/products/new') %>">
                <%= link_to "/products/new" do %>
                <i class="fa fa-money"></i> <span class="nav-label">我要卖</span>
                <% end %>
            </li>




            <li style="margin-top: 10px;text-align:center">
              <img src="/images/wechat.jpg" style="width: 80%"/>
            </li>
            <!-- <li style="position: fixed;margin-left: 20px;margin-top: 5px;">
              <img src="/images/wechat.jpg" style="width: 70%"/>
            </li> -->


        </ul>

    </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">



            <%= form_tag({:controller => "products", :action => "search"}, method: "get",class: "navbar-form-custom",style:"width:auto") do %>
            <button class="minimalize-styl-2 btn btn-primary " type="submit" style="margin-right:0px"><i class="fa fa-search"></i> </button>
              <%= text_field_tag :query, params[:query], size: 30 , placeholder: "试一试搜索吧~",style:"float: left;padding: 4px 12px;margin: 14px 5px 5px 2px;"%>
            <% end %>


        </div>
        <div class= "pull-right">
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <%= link_to lottery_wheel_path do %>
                    <i class="fa fa-gift"></i> 抽奖
                <% end %>
            </li>
            <li>
                <%= link_to  home_index_path  do %>
                    <i class="fa fa-home"></i> 首页
                <% end %>
            </li> 
            <li>
                <%= link_to user_edit_show_path do %>
                    <i class="fa fa-user"></i> 个人资料
                <% end %>
            </li>
            <li>
                <%= link_to orders_path do %>
                    <i class="fa fa-archive"></i> 我买的
                <% end %>
            </li>
            <li>
                <%= link_to products_for_sale_path do %>
                    <i class="fa fa-money"></i> 我卖的
                <% end %>
            </li>
            <li>
                <%= link_to collections_show_path  do %>
                    <i class="fa fa-star"></i> 收藏
                <% end %>
            </li>
            <li>
                <%= link_to( destroy_user_session_path, method: :delete) do %>
                    <i class="fa fa-sign-out"></i> 登出
                <% end %>
            </li>
        </ul>
      </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>THUPost</title>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body>

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        <%= render 'layouts/navigation' %>

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>
 <!--
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
-->
            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->


        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>THUPost</title>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body class="login-page">

    <!-- Wrapper-->
    <div id="wrapper">
      <%= yield %>
    </div>
    <!-- End wrapper-->
      <%= yield :javascript %>
</body>
</html>